"""empty message

Revision ID: 228d09acd80c
Revises: 22c4bc806c8b
Create Date: 2019-12-20 15:34:41.234648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228d09acd80c'
down_revision = '22c4bc806c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
